### ISSUE TITLE
Changing Action Space to match the Openai Gym environments.

### ISSUE THREAD

**Issue by batu** [openai/retro#124]
## Issue summary
I am trying to train Atari Breakout, but for my use case, I need to be able to work with Retro, while keeping the results comparable to the standard training structure.

However, the gym Atari has a Discrete(4) action space whereas the Retro version has a MultiBinary[11]. Of course, this means that they are wildly different tasks, difficulty wise. 

What is the proper way to change the gym-retro action spaces? Couldn't find the necessary hooks in the JSON files. 

Thank you!

**Comment by christopherhesse** [comment]
`retro.make(game=game, use_restricted_actions=retro.Actions.DISCRETE)`

It won't be the same number of actions since ALE uses the minimal action set, which is defined on a per-game basis.  You can use something like https://gist.github.com/christopherhesse/8e5c63c3b0007f4c3e333c6a158872cf to turn a multibinary into a discrete with whatever actions you want.  If there was a json file with the per-game allowed combos for ALE, I would be willing to add it to gym-retro somewhere (probably as a wrapper).

**Comment by batu** [comment]
Thank you!
