### ISSUE TITLE
Super Mario World resets after level 1.

### ISSUE THREAD

**Issue by batu** [openai/retro#126]
## Issue summary

I apologize for opening so many issues, I am trying to understand more concretely the parameters that govern how the games are played out.

This time I am training an agent that is playing SMW and it is doing well! But, the training seems to reset after level 1. 

Can you help me make sure the game only resets when the character has 0 life? (And that seems to be the outlined concept in the scenario!

Thank you very much,

**Comment by christopherhesse** [comment]
Looks like the lives variable was incorrect, thanks for the bug report!  https://github.com/openai/retro/commit/85e3de5417ba7bcb9d93b0fa8d1ad5017ac49d9e

**Comment by christopherhesse** [comment]
Let me know if that doesn't fix the issue.

**Comment by batu** [comment]
Thank you! I just checked and it works!

Would it be possible for you to help me give a negative reward every time Mario dies?

```
  "reward": {
    "variables": {
      "score": {
        "reward": 10.0
      },
      "lives": {
        "measurement":"delta",
        "reward": 10.0
      }
    }
  }
```
This is what I am testing out, with the intention that if a live is lost the delta will be -1 and that will be multiplied by the reward, effectively becoming a punishment.

Also, what was the reasoning behind changing the reward from 1 to 10?

Thank you in advance!

**Comment by christopherhesse** [comment]
I answered your reward 1 to 10 question on your other comment.

For the negative reward on death, that seems fine.  I would use "penalty": 10 instead of "reward" though.  And scaling that relative to score might be hard.  I'm not sure what you mean by "multiplied by the reward" though.  You may also consider ending the episode on the first death rather than messing around with a per-life punishment.
