### ISSUE TITLE
Cannot load game to Integration

### ISSUE THREAD

**Issue by dotunadegbite** [openai/retro#159]
## Issue summary

When loading a rom to the integration UI the screen stays gray and nothing happens. 

## System information

- Windows 10
- 3.7
- 0.6.0

**Comment by christopherhesse** [comment]
This worked fine for me, but I had to copy the integration UI to the path `import retro; print(retro.__path__)`

Are there any errors?

**Comment by jdiazgon** [comment]
Hi @christopherhesse, I'm getting the same issue as mentioned above.

First of all, when I run for the first time the Windows integration UI, I get the following error:
![image](https://user-images.githubusercontent.com/31688036/60402086-ca19ee80-9b8a-11e9-9eb0-662c9b4466dd.png)

In order to avoid this issue, I have to manually create a `data` folder in the location of the exe.

After fixing that, I try to load a ROM and the screen stays gray. I'm using version `0.7.1` in my Windows 10.

**Comment by christopherhesse** [comment]
Try the install guide https://retro.readthedocs.io/en/latest/getting_started.html

**Comment by jdiazgon** [comment]
Okay, that did the trick. I had to move the exe file to the location of `gym-retro`. Thanks :)
