### ISSUE TITLE
Pong-Atari2600 vs PongNoFrameskip-v4 Performance

### ISSUE THREAD

**Issue by MatPoliquin** [openai/retro#178]
## Issue summary

Using PPO2 Pong-Atari2600 after a million timesteps will still be stuck just bellow -21
while PongNoFrameskip-v4 will already be around -17

looking at the monitor files for Pong-Atari2600 doesn't seem to return positive rewards as often

Note: I disabled StochasticFrameSkip so it is on par with PongNoFrameskip-v4. Even when turned on the results are the same.

EDIT:
`python3 -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=2e7`
`python3 -m baselines.run --alg=ppo2 --env=Pong-Atari2600 --num_timesteps=2e7`

I trained both for 20M frames, attached their respective progress.csv report
[Pong-Atari2600.zip](https://github.com/openai/retro/files/3483988/Pong-Atari2600.zip)
[PongNoFrameskip-v4.zip](https://github.com/openai/retro/files/3483989/PongNoFrameskip-v4.zip)

PongNoFrameSkip-v4 = 20.86
Pong-Atari2600 = 15.65

info:
gym-retro 0.7.0
gym 0.14.0
Ubuntu 18.10

**Comment by christopherhesse** [comment]
It's not clear that this is specifically a retro issue, but here are some differences:

atari_py and retro envs are treated differently by baselines:

https://github.com/openai/baselines/blob/master/baselines/common/cmd_util.py#L62

* atari_py gets `make_atari` and `wrap_deepmind`
  * This has no-op resets
   * This will max frames together to account for flickering
* retro gets `make_retro` and `wrap_deepmind_retro`
  * This has `StochasticFrameSkip`, did you disable it by setting `n=0`?  Otherwise the frameskip won't happen at all.
  * This also may stack frames by default, it's unclear to me if that happens

In addition, retro envs by default use a multibinary action space, while ALE uses a minimal discrete one.   You can tell retro to use discrete actions using this: https://retro.readthedocs.io/en/latest/python.html#actions and you can tell ALE to use the full set of discrete actions with `full_action_space=True`: https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py#L34

It's a bit confusing that baselines treats these differently.   One difference is that retro does not have the minimal action sets defined for atari games (or any other games) as mentioned in this issue: https://github.com/openai/retro/issues/127 since they have to be determined on a game-by-game basis.

**Comment by MatPoliquin** [comment]
I disabled the frameskip by commenting it out, I also tried with the default n=4, same result

Thanks for the detailed answer, makes sense, I forgot about the action space differences

**Comment by christopherhesse** [comment]
Er, sorry I wrote the wrong thing for `StochasticFrameSkip`.  The line is here: https://github.com/openai/baselines/blob/master/baselines/common/retro_wrappers.py#L207 and what I meant to say is that you should set `stickprob=0`, removing the wrapper entirely or settings `n=0` changes the RL problem substantially.

**Comment by christopherhesse** [comment]
I also noticed that `EpisodicLifeEnv` is applied in `wrap_deepmind` but there is no equivalent wrapper in `wrap_deepmind_retro`.  This probably doesn't affect pong.

**Comment by christopherhesse** [comment]
Closing this, please re-open if there is evidence that this is a retro issue.

**Comment by nfkok** [comment]
> ## Issue summary
> Using PPO2 Pong-Atari2600 after a million timesteps will still be stuck just bellow -21
> while PongNoFrameskip-v4 will already be around -17
> 
> looking at the monitor files for Pong-Atari2600 doesn't seem to return positive rewards as often
> 
> Note: I disabled StochasticFrameSkip so it is on par with PongNoFrameskip-v4. Even when turned on the results are the same.
> 
> EDIT:
> `python3 -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=2e7`
> `python3 -m baselines.run --alg=ppo2 --env=Pong-Atari2600 --num_timesteps=2e7`
> 
> I trained both for 20M frames, attached their respective progress.csv report
> [Pong-Atari2600.zip](https://github.com/openai/retro/files/3483988/Pong-Atari2600.zip)
> [PongNoFrameskip-v4.zip](https://github.com/openai/retro/files/3483989/PongNoFrameskip-v4.zip)
> 
> PongNoFrameSkip-v4 = 20.86
> Pong-Atari2600 = 15.65
> 
> info:
> gym-retro 0.7.0
> gym 0.14.0
> Ubuntu 18.10

Hi, may I know where did you find the ROM for PongNoFrameskip-v4?

I am actually facing an issue. I implemented the same thing as the code in Andrej Karpathy's Git [,](https://gist.github.com/karpathy/a4166c7fe253700972fcbc77e4ea32c5) just a little bit modification to map the action space in Pong-Atari2600, but my agent is totally not improving. I want to test the same thing using PongNoFrameskip-v4 to see whether the same issue exist.

Thanks.
